### ISSUE TITLE
ImportError: /home/tione/notebook/envs/taac2021-tagging/lib/python3.7/site-packages/detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass

### ISSUE THREAD

**Issue by ZJJHYM** [linjieli222/HERO_Video_Feature_Extractor#3]
ImportError: /home/tione/notebook/envs/taac2021-tagging/lib/python3.7/site-packages/detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass

这是什么原因，换了两个平台都不行

**Comment by linjieli222** [comment]
Hi @ZJJDJJ ,

Thanks for your interests in this project. 

If you follow the instructions to use our provided Docker image, you should have not met this error. All packages are pre-installed inside the Docker image. 

For detectron2 installation, they have provided the full instructions and related FAQ in their repo: https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md. Please redirect your questions to their repo. 

Please note that if you are installing with a different pytorch version, there is no guarantee that the resulting features would be the same as what we provided in HERO. 

Thanks.

**Comment by ZJJHYM** [comment]
Thank you!I solved this problem through your idea.Now I got another problem:
`ffprobe failed at: /datasets/algo-2021/dataset/videos/train_5k/43dfa1a82798608aaae99643bd9b33be.mp4`
It happen on extract.py,line 254-255
```
        loader.reset_state()
        n_dataset = len(dataset)
```
Thanks!
